### ISSUE TITLE
Implement cleanup of pods of jobs that are finished

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-job-scheduler#87]
Pre-requisite - Logs for completed jobs

Pods of completed or failed jobs keep log, which is valuable. However when job component is configured to use volumeMount, persistent volume is bound to this pod and it cannot be deleted/released while the pod exist.
Delete pods for completed or failed jobs, older then one day to clean up resources. Logs will be available from Analytics Workspaces

DoD:
Job Pods deleted x hrs after completed/finished, x as settings

**Comment by satr** [comment]
Implemented. Jobs and its pod will be automatically deleted by the Kubernetes job controller after 24 hours, because JobSpec property `TTLSecondsAfterFinished: 86400` in scheduled jobs
